port: "8000"
maxHeaderBytes: "1048576"
readTimeout: "10s"
writeTimeout: "10s"

db:
  username: "postgres"
  # host: "db"
  # port: "5432"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
